name: increment version

on:
  workflow_dispatch:

jobs:
  increment-version:
    if: github.actor != 'jake94a'
    runs-on: ubuntu-20.04
    steps:
      - name: echo actor
        run: |
          echo ${{ github.actor }}

      - name: if actor is me, skip
        if: ${{ github.actor }} != 'jake94a'
        env:
          ACTOR: ${{ github.actor }}
        run: |
          if [ $ACTOR = 'jake94a' ]; then exit 1; fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MASTER_KEY }}

      - name: increment patch version
        shell: bash
        run: |
          python $GITHUB_WORKSPACE/.github/workflows/increment_version.py

      - name: push new version
        env:
          COMMIT_USERNAME: Jake Anderson
          COMMIT_USER_EMAIL: 54042868+jake94a@users.noreply.github.com
          NEW_VER: ${{ env.NEW_VER }} # this comes from the python script
          BRANCH_NAME: ${{ github.ref_name }}
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
        run: |
          echo "$MASTER_KEY" > token.txt
          gh auth login --with-token < token.txt
          git config --global user.name $COMMIT_USERNAME
          git config --global user.email $COMMIT_USER_EMAIL
          git config --global credential.helper '!f() { echo "password=$MASTER_KEY"; }; f'
          git add .
          git commit -m "new version $NEW_VER"
          git push origin $BRANCH_NAME
